### ISSUE TITLE
Start/stop qjackctl with fork/exec and kill during app startup/shutdown

### ISSUE THREAD

**Issue by mjrousos** [mjrousos/AudioProcessor#2]

**Comment by mjrousos** [comment]
@stfritz84, qjackctl and ecasound should both startup correctly now when starting this program (and shutdown when exiting it). I'm getting some errors from jackctl because I think I don't have it configured correctly on my machine, but the process appears to be starting/stopping correctly. If you get a chance, can you grab the latest version of this code to see if it's working as expected?

Note that I still have it just hard-coding a 'start' and 'stop' with a short pause in between because I have yet to write the logic that will allow controlling that with keyboard input.

**Comment by Stfritz84** [comment]
Had to change the path for the applications. But other than that, works fine! I did notice when the path was wrong I got the error msg, but it went to the next step anyways.
