### ISSUE TITLE
Figure out how to use GPIO to notify users (with LEDs) and receive input (with buttons)

### ISSUE THREAD

**Issue by mjrousos** [mjrousos/AudioProcessor#4]

**Comment by Stfritz84** [comment]
There are 8 pins that can be assigned as inputs or outputs. Since they are limited a latch/unlatch arrangement could be used for the arm/disarm? And use the ready led for the in rec mode when flashing. The available pins are named according to the chart at http://wiki.wandboard.org/index.php/External_gpios We can only use the ones that are on JP-4 pin connector. I will look into the circuit required to drive them.

**Comment by mjrousos** [comment]
Sounds good. I found [this](http://bec-systems.com/site/281/how-to-implement-an-interrupt-driven-gpio-input-in-linux) linked from that wiki which may be helpful for writing the code necessary to interact with the pins. It sounds like we can get callbacks when the state of a pin changes (either direction), so arm/disarm on button up/down should work (is that what you mean by latch/unlatch?). We could probably do the same with start/stop record if you like.

**Comment by Stfritz84** [comment]
Not sure what they are doing in that link.

I am able to turn on an LED with the following as long as I am root:
echo 75 >/sys/class/gpio/export //creates link to pin 4 
echo out >/sys/class/gpio/gpio75/direction //sets to output
echo 1 >/sys/class/gpio/gpio75/value //sets to 1
//After this you are supposed to do an unexport to remove the link.

I found a script that is supposed to blink the LED:
#!/bin/bash sudo

GPIO=75
GPIODIR=/sys/class/gpio/gpio$GPIO

echo "Configuring GPIO $GPIO"

#check if the gpio is already exported
if [ ! -e "$GPIODIR" ]
then
    echo "Exporting GPIO"
    echo $GPIO > /sys/class/gpio/export
else
    echo "GPIO already exported"
fi

echo "Current direction: `cat $GPIODIR/direction`"
echo "Set GPIO as output"
echo out > $GPIODIR/direction
echo "New GPIO direction: `cat $GPIODIR/direction`"
echo "Current value: `cat $GPIODIR/value`"
echo "Set value as high"
echo 1 > $GPIODIR/value
echo "New value: `cat $GPIODIR/value`"

#Endless loop
echo "Start blinking, 1 sec on plus 1 sec off, press CTRL+C to end"
while ( true );
    do echo 1 > $GPIODIR/value;
    cat $GPIODIR/value;
    sleep 1;
    echo 0 > $GPIODIR/value;
    cat $GPIODIR/value;
    sleep 1;
done;

**Comment by Stfritz84** [comment]
Most small buttons are momentary style, so are only active when held. As far as the arm/disarm, I think that the first arm would happen automatically(apps started waiting for start). If the arm button is pressed again it would exit, if it was pressed again it would reset the whole program(or could just cycle power). Open to suggestions. Also fine if start stop is shared button. I am going to work on the input circuit next.

**Comment by mjrousos** [comment]
Ah, that makes sense. Yea, that should be no problem. Our program already can tell whether the recording is armed or not (if ecasoundStdIn has a value, then ecasound is running, therefore recording is armed), so it should be really simple to just have one button that arms if recording isn't armed yet and vice-versa.

We can do the same for recording if you like. All we'd need to do would be to add one more boolean variable to track whether or not we're in a recording state (so that we know what to do in case of a button press). I think either that or separate buttons would be equally simple to setup; probably limiting it to one button makes sense since we have limited pins to work with.

**Comment by Stfritz84** [comment]
I think consolidating the buttons is best, not much real estate on the case.  I ran your latest version, worked very well. I figured out how to change the rec directory, just place the path in front of the file name. Don't know why l didn't try that before. I got desperate after I overloaded the partition and had to start with a fresh image for the 3rd time.
